spring:
  application:
    name: yu-ai-code-mother-backend
server:
  port: 8123
  servlet:
    context-path: /api



# knife4j 配置参数
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.wanan.yuaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
